apiVersion: v2
name: seafile
description: Helm chart for Seafile - Pro and Community Edition
type: application
version: "13.0.19-8"
appVersion: "13.0.19"
home: https://ioanalytica.com
sources:
  - https://github.com/ioanalytica/seafile-helm
maintainers:
  - name: ioanalytica
icon: https://github.com/ioanalytica/seafile-helm/seafile_logo.svg
