apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seafile.fullname" . }}-ccnet
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
data:
  ccnet.conf: |
    [General]

    [Database]
    ENGINE = mysql
    HOST = {{ include "seafile.database.host" . }}
    PORT = {{ include "seafile.database.port" . }}
    USER = {{ .Values.seafile.database.user }}
    PASSWD = __SEAFILE_MYSQL_DB_PASSWORD__
    DB = {{ .Values.seafile.database.ccnetDbName }}
    CONNECTION_CHARSET = utf8
