apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seafile.fullname" . }}-seafile-conf
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
data:
  seafile.conf: |
    [fileserver]
    port = 8082

    [database]
    type = mysql
    host = {{ include "seafile.database.host" . }}
    port = {{ include "seafile.database.port" . }}
    user = {{ .Values.seafile.database.user }}
    password = __SEAFILE_MYSQL_DB_PASSWORD__
    db_name = {{ .Values.seafile.database.seafileDbName }}
    connection_charset = utf8

    {{- if .Values.seafile.cluster.enabled }}

    [cluster]
    enable = true
    {{- end }}

    [notification]
    enabled = {{ if .Values.seafile.notification.enabled }}true{{ else }}false{{ end }}
    host = 127.0.0.1
    port = 8083
    log_level = info
    jwt_private_key = __JWT_PRIVATE_KEY__
