{{- if not .Values.seafile.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "seafile.fullname" . }}-secret
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
stringData:
  JWT_PRIVATE_KEY: {{ .Values.seafile.jwt.privateKey | quote }}
  SEAFILE_MYSQL_DB_PASSWORD: {{ .Values.seafile.database.password | quote }}
  {{- if or .Values.seafile.initMode (eq .Values.seafile.database.mode "internal") }}
  INIT_SEAFILE_ADMIN_PASSWORD: {{ .Values.seafile.admin.password | quote }}
  INIT_SEAFILE_MYSQL_ROOT_PASSWORD: {{ .Values.seafile.database.rootPassword | quote }}
  {{- end }}
  {{- if or (eq .Values.seafile.cache.mode "internal") (and (eq .Values.seafile.cache.provider "redis") (not .Values.seafile.cache.redis.existingSecret)) }}
  REDIS_PASSWORD: {{ .Values.seafile.cache.redis.password | quote }}
  {{- end }}
  {{- if and (eq .Values.seafile.cache.provider "memcached") (not .Values.seafile.cache.memcached.existingSecret) .Values.seafile.cache.memcached.password }}
  MEMCACHED_PASSWORD: {{ .Values.seafile.cache.memcached.password | quote }}
  {{- end }}
  {{- if and (eq .Values.seafile.edition "pro") (eq .Values.seafile.storage.type "s3") }}
  S3_SECRET_KEY: {{ .Values.seafile.storage.s3.secretKey | quote }}
  S3_SSE_C_KEY: {{ .Values.seafile.storage.s3.sseCKey | quote }}
  {{- end }}
  {{- if and (eq .Values.seafile.edition "pro") .Values.seafile.seahub.ldap.enabled .Values.seafile.seahub.ldap.adminPassword }}
  LDAP_ADMIN_PASSWORD: {{ .Values.seafile.seahub.ldap.adminPassword | quote }}
  {{- end }}
  {{- if and .Values.seafile.elasticsearch.enabled (ne .Values.seafile.elasticsearch.mode "internal") .Values.seafile.elasticsearch.password }}
  ES_PASSWORD: {{ .Values.seafile.elasticsearch.password | quote }}
  {{- end }}
{{- end }}
