apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.fullname" . }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
spec:
  type: {{ .Values.seafile.service.type }}
  {{- if and (eq .Values.seafile.service.type "LoadBalancer") .Values.seafile.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.seafile.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "seafile.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
